### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 40 but got size 39 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by powercen** [kijai/ComfyUI-FramerWrapper#3]
pred_tracks: torch.Size([14, 5, 2])
controlnet_cond_scale: 1.0
!!! Exception during processing !!! Sizes of tensors must match except in dimension 1. Expected size 40 but got size 39 for tensor number 1 in the list.
Traceback (most recent call last):
  File "C:\Program Files\ComfyUI-aki-v1.5\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\Program Files\ComfyUI-aki-v1.5\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\Program Files\ComfyUI-aki-v1.5\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Program Files\ComfyUI-aki-v1.5\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\Program Files\ComfyUI-aki-v1.5\custom_nodes\ComfyUI-FramerWrapper\nodes.py", line 231, in process
    video_frames = model(
  File "C:\Program Files\ComfyUI-aki-v1.5\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Program Files\ComfyUI-aki-v1.5\custom_nodes\ComfyUI-FramerWrapper\pipeline_stable_video_diffusion_interp_control.py", line 659, in __call__
    outputs = self.unet(
  File "C:\Program Files\ComfyUI-aki-v1.5\python\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Program Files\ComfyUI-aki-v1.5\python\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Program Files\ComfyUI-aki-v1.5\custom_nodes\ComfyUI-FramerWrapper\models_diffusers\unet_spatio_temporal_condition.py", line 538, in forward
    sample = upsample_block(
  File "C:\Program Files\ComfyUI-aki-v1.5\python\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Program Files\ComfyUI-aki-v1.5\python\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Program Files\ComfyUI-aki-v1.5\custom_nodes\ComfyUI-FramerWrapper\models_diffusers\unet_3d_blocks.py", line 2361, in forward
    hidden_states = torch.cat([hidden_states, res_hidden_states], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 40 but got size 39 for tensor number 1 in the list.

**Comment by kijai** [comment]
Not sure yet, but I think the video resolution has to be divisible by 64.
